# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
# - name: skipPreJobTask
#   value: true
# - name: skipPostJobTask
#   value: true
- name: skipPostCheckoutTask
  value: true

stages:

  - stage: Stage_A
    displayName: Deploy Management Groups Stage
  
    jobs:

    - job: Job_1
      steps:
      - task: PowerShell@2
        displayName: 'Error out'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.logissue type=error;]Always fail"
            Write-Host "##vso[task.complete result=Failed;]Failure triggered. $reason" -ForegroundColor Red
      - script: |
          echo Stage-A, Job-1, Step-1
        condition: succeededOrFailed()
      - script: |
          echo Stage-A, Job-1, Step-2

    - job: Job_2
      dependsOn: Job_1
      steps:
      - script: |
          echo Stage-A, Job-2, Step-1
      - script: |
          echo Stage-A, Job-2, Step-2
    